module.exports = {
  NOKIA_CONSUMER_KEY: process.env.NOKIA_CONSUMER_KEY,
  NOKIA_CLIENT_ID: process.env.NOKIA_CLIENT_ID,
	NOKIA_SECRET: process.env.NOKIA_SECRET,
	NOKIA_CONSUMER_SECRET: process.env.NOKIA_CONSUMER_SECRET,
	CALLBACK_BASE: "https://martinchapman.co.uk",
	NOKIA_REQUEST_TOKEN_BASE: "https://developer.health.nokia.com/account/request_token",
	NOKIA_AUTHORISATION_BASE: "https://developer.health.nokia.com/account/authorize",
	NOKIA_AUTHORISATION_BASE_V2: "https://account.health.nokia.com/oauth2_user/authorize2",
	NOKIA_ACCESS_TOKEN_BASE: "https://developer.health.nokia.com/account/access_token",
	NOKIA_ACCESS_TOKEN_BASE_OAUTH2: "https://account.health.nokia.com/oauth2/token",
	SUBSCRIPTION_BASE: "https://api.health.nokia.com/notify",
	TYPES: { "getactivity": "activities", "getmeas": "measuregrps", "getintradayactivity": "series", "getsummary": "" },
	URLS: { "getmeas": "https://api.health.nokia.com/measure", "getactivity": "https://api.health.nokia.com/v2/measure", "getintradayactivity": "https://api.health.nokia.com/v2/measure", "getsummary": "https://api.health.nokia.com/v2/sleep" },
	START: { "getmeas": "startdate", "getactivity": "startdateymd", "getintradayactivity": "startdate", "getsummary": "startdateymd" },
	END: { "getmeas": "enddate", "getactivity": "enddateymd", "getintradayactivity": "enddate", "getsummary": "enddateymd" },
	USERNAME: process.env.USERNAME,
	PASSWORD: process.env.PASSWORD,
	OAUTH_VERSION: 2,
	CONVERT_OAUTH: false,
  SENSOR_TO_FHIR_URL: 'http://localhost:3001/'
};
